package edu.weblibrary.server.persistence.cayenne.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import edu.weblibrary.server.persistence.cayenne.Book;

/**
 * Class _Author was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Author extends CayenneDataObject {

    public static final String BIRTH_YEAR_PROPERTY = "birthYear";
    public static final String ID_PROPERTY = "id";
    public static final String NAME_PROPERTY = "name";
    public static final String PATRONYMIC_PROPERTY = "patronymic";
    public static final String SURNAME_PROPERTY = "surname";
    public static final String BOOK_ARRAY_PROPERTY = "bookArray";

    public static final String ID_PK_COLUMN = "id";

    public void setBirthYear(Integer birthYear) {
        writeProperty("birthYear", birthYear);
    }
    public Integer getBirthYear() {
        return (Integer)readProperty("birthYear");
    }

    public void setId(Integer id) {
        writeProperty("id", id);
    }
    public Integer getId() {
        return (Integer)readProperty("id");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setPatronymic(String patronymic) {
        writeProperty("patronymic", patronymic);
    }
    public String getPatronymic() {
        return (String)readProperty("patronymic");
    }

    public void setSurname(String surname) {
        writeProperty("surname", surname);
    }
    public String getSurname() {
        return (String)readProperty("surname");
    }

    public void addToBookArray(Book obj) {
        addToManyTarget("bookArray", obj, true);
    }
    public void removeFromBookArray(Book obj) {
        removeToManyTarget("bookArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Book> getBookArray() {
        return (List<Book>)readProperty("bookArray");
    }


}
