package edu.weblibrary.server.persistence.cayenne.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import edu.weblibrary.server.persistence.cayenne.Author;

/**
 * Class _Book was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Book extends CayenneDataObject {

    public static final String ARRIVAL_DATE_PROPERTY = "arrivalDate";
    public static final String AUTHOR_ID_PROPERTY = "authorId";
    public static final String ID_PROPERTY = "id";
    public static final String KEYWORDS_PROPERTY = "keywords";
    public static final String NUMBER_PROPERTY = "number";
    public static final String PRICE_PROPERTY = "price";
    public static final String PUBLICATION_YEAR_PROPERTY = "publicationYear";
    public static final String PUBLISHING_PROPERTY = "publishing";
    public static final String TITLE_PROPERTY = "title";
    public static final String TO_AUTHOR_PROPERTY = "toAuthor";

    public static final String ID_PK_COLUMN = "id";

    public void setArrivalDate(Date arrivalDate) {
        writeProperty("arrivalDate", arrivalDate);
    }
    public Date getArrivalDate() {
        return (Date)readProperty("arrivalDate");
    }

    public void setAuthorId(Integer authorId) {
        writeProperty("authorId", authorId);
    }
    public Integer getAuthorId() {
        return (Integer)readProperty("authorId");
    }

    public void setId(Integer id) {
        writeProperty("id", id);
    }
    public Integer getId() {
        return (Integer)readProperty("id");
    }

    public void setKeywords(String keywords) {
        writeProperty("keywords", keywords);
    }
    public String getKeywords() {
        return (String)readProperty("keywords");
    }

    public void setNumber(Integer number) {
        writeProperty("number", number);
    }
    public Integer getNumber() {
        return (Integer)readProperty("number");
    }

    public void setPrice(Double price) {
        writeProperty("price", price);
    }
    public Double getPrice() {
        return (Double)readProperty("price");
    }

    public void setPublicationYear(Integer publicationYear) {
        writeProperty("publicationYear", publicationYear);
    }
    public Integer getPublicationYear() {
        return (Integer)readProperty("publicationYear");
    }

    public void setPublishing(String publishing) {
        writeProperty("publishing", publishing);
    }
    public String getPublishing() {
        return (String)readProperty("publishing");
    }

    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }

    public void setToAuthor(Author toAuthor) {
        setToOneTarget("toAuthor", toAuthor, true);
    }

    public Author getToAuthor() {
        return (Author)readProperty("toAuthor");
    }


}
